[project]
name = "ra9"
version = "0.2.0"
description = "A tool to automate downloading attachments from ra9.jp and ra9plus.jp."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "selenium",
]
